const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync(new URL('../dist/index.html', `file://${__filename}`), 'utf8');
const script = html.match(/<script>\n([\s\S]*?)\n<\/script>/)[1].replace('window.addEventListener(\'hashchange\',render);loadData();','');
const elements = new Map();
const element = id => {
  if (!elements.has(id)) elements.set(id, {innerHTML:'', textContent:'', classList:{toggle(){},add(){},remove(){}}});
  return elements.get(id);
};
const stock = {code:'000001', name:'검증 종목', entry_date:'2026-09-01', entry_price:100, current:100, stop:100, shares:1, pnl_pct:0, hist:[]};
const summary = {open_count:1,closed_count:1,net_pnl_won:0,return_on_seed_pct:0,realized_won:0,unrealized_won:0,win_rate:100,avg_win_pct:3.2,avg_loss_pct:0};
const account = {seed:1000,forward:{start_date:'2026-09-01',open:[stock],closed:[],summary}, historical:{summary:{closed_count:60,win_rate:100,realized_won:6000,profit_loss_ratio:null,profit_loss_ratio_status:'no_losing_trades'},coverage:{complete:true},all_time_summary:{closed_count:61,win_rate:50,realized_won:5980,pl_ratio:99}}};
const payload = {meta:{generated_at:'2026-10-01 13:48:04'}, accounts:{ks_mid:account,kq_mid:structuredClone(account)}};
const context = {payload,document:{getElementById:element,querySelector:()=>element('status')},window:{scrollTo(){}},location:{hash:''},URLSearchParams,console};
vm.createContext(context);
vm.runInContext(script,context);
vm.runInContext('DATA=payload;renderStock("ks_mid","000001")',context);
assert.match(element('app').innerHTML,/보유 기준 유지/);
assert.doesNotMatch(element('app').innerHTML,/<div class="decision-title">보호선 이탈<\/div>/);
stock.current=99;
vm.runInContext('renderStock("ks_mid","000001")',context);
assert.match(element('app').innerHTML,/보호선 이탈/);
stock.current=110;stock.stop=105;
vm.runInContext('renderStock("ks_mid","000001")',context);
assert.match(element('app').innerHTML,/수익 보호 구간/);
const history=vm.runInContext('historicalPerformance(DATA.accounts.ks_mid)',context);
assert.match(history,/60건/);
assert.doesNotMatch(history,/61건|5,980|99/);
assert.match(history,/6,000원|6,000/);
assert.match(history,/산출 불가/);
assert.match(history,/손실 거래 없음/);
account.historical.summary.profit_loss_ratio=2.46;
account.historical.summary.profit_loss_ratio_status='ok';
assert.match(vm.runInContext('historicalPerformance(DATA.accounts.ks_mid)',context),/2\.46/);
account.historical.coverage.complete=false;
assert.match(vm.runInContext('historicalPerformance(DATA.accounts.ks_mid)',context),/전체 기록이 확인되지/);
delete account.historical.summary;
assert.doesNotMatch(vm.runInContext('historicalPerformance(DATA.accounts.ks_mid)',context),/61건|5,980/);
console.log('performance display tests passed: equality, breach, protection, separate history, unavailable ratio, incomplete history');
