const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync(new URL('../dist/index.html', `file://${__filename}`), 'utf8');
const script = html.match(/<script>\n([\s\S]*?)\n<\/script>/)[1].replace('window.addEventListener(\'hashchange\',render);loadData();','');
const elements = new Map();
const element = id => {
  if (!elements.has(id)) elements.set(id, {innerHTML:'', textContent:'', classList:{toggle(){},add(){},remove(){}}});
  return elements.get(id);
};
const stock = {code:'000001', name:'검증 종목', entry_date:'2026-09-01', entry_price:100, current:100, stop:100, shares:1, pnl_pct:0, hist:[]};
const summary = {open_count:1,closed_count:1,net_pnl_won:0,return_on_seed_pct:0,realized_won:0,unrealized_won:0,win_rate:100,avg_win_pct:3.2,avg_loss_pct:0};
const account = {seed:1000,forward:{start_date:'2026-09-01',open:[stock],closed:[],summary}, historical:{summary:{closed_count:60,win_rate:100,realized_won:6000,profit_loss_ratio:null,profit_loss_ratio_status:'no_losing_trades'},coverage:{complete:true},all_time_summary:{closed_count:61,win_rate:50,realized_won:5980,pl_ratio:99}}};
const payload = {meta:{generated_at:'2026-10-01 13:48:04'}, accounts:{ks_mid:account,kq_mid:structuredClone(account)}};
const context = {payload,document:{getElementById:element,querySelector:()=>element('status')},window:{scrollTo(){}},location:{hash:''},URLSearchParams,console};
vm.createContext(context);
vm.runInContext(script,context);
vm.runInContext('DATA=payload;renderStock("ks_mid","000001")',context);
assert.match(element('app').innerHTML,/보유 기준 유지/);
assert.doesNotMatch(element('app').innerHTML,/<div class="decision-title">보호선 이탈<\/div>/);
stock.current=99;
vm.runInContext('renderStock("ks_mid","000001")',context);
assert.match(element('app').innerHTML,/보호선 이탈/);
stock.current=110;stock.stop=105;
vm.runInContext('renderStock("ks_mid","000001")',context);
assert.match(element('app').innerHTML,/수익 보호 구간/);
const history=vm.runInContext('historicalPerformance(DATA.accounts.ks_mid)',context);
assert.match(history,/60건/);
assert.doesNotMatch(history,/61건|5,980|99/);
assert.match(history,/6,000원|6,000/);
assert.match(history,/산출 불가/);
assert.match(history,/손실 거래 없음/);
account.historical.summary.profit_loss_ratio=2.46;
account.historical.summary.profit_loss_ratio_status='ok';
assert.match(vm.runInContext('historicalPerformance(DATA.accounts.ks_mid)',context),/2\.46/);
account.historical.coverage.complete=false;
assert.match(vm.runInContext('historicalPerformance(DATA.accounts.ks_mid)',context),/전체 기록이 확인되지/);
delete account.historical.summary;
assert.doesNotMatch(vm.runInContext('historicalPerformance(DATA.accounts.ks_mid)',context),/61건|5,980/);
account.balance={available:true,cash_won:700,holdings_value_won:500,account_value_won:1200};
account.equity_tracking={available:true,baseline_at:'2026-10-01 13:48:04',baseline_value_won:1000,equity_change_won:200,equity_change_pct:20};
account.seed=500;
summary.net_pnl_won=-100;summary.return_on_seed_pct=-20;
payload.combined_balance=account.balance;
payload.combined_equity_tracking=account.equity_tracking;
payload.combined_forward={seed:1000,net_pnl_won:-100,return_on_seed_pct:-10,realized_won:-110,unrealized_won:10};
vm.runInContext('renderAccount("ks_mid","hold")',context);
assert.match(element('app').innerHTML,/현재 총자산/);
assert.match(element('app').innerHTML,/1,200원/);
assert.match(element('app').innerHTML,/700원/);
assert.match(element('app').innerHTML,/포워드 거래손익/);
assert.match(element('app').innerHTML,/종잣돈 대비 손익률/);
assert.doesNotMatch(element('app').innerHTML,/<span>계좌 손익<\/span>/);
assert.match(element('app').innerHTML,/자산 변동 \+200원 \(\+20\.00%\)/);
assert.match(element('app').innerHTML,/입출금 조정 전/);
assert.match(vm.runInContext('trackingSummary({available:false})',context),/기준을 확인 중/);
assert.doesNotMatch(vm.runInContext('trackingSummary({available:false})',context),/0원|0\.00%/);
vm.runInContext('renderHome()',context);
assert.match(element('app').innerHTML,/<div class="overview-label">현재 총자산<\/div>/);
assert.match(element('app').innerHTML,/1,200원/);
vm.runInContext('renderPerformance()',context);
assert.match(element('app').innerHTML,/종잣돈 대비 손익률/);
assert.match(element('app').innerHTML,/기간 시작 잔고 대비 계좌 수익률과 구분/);
console.log('performance display tests passed: stop boundary, separate history, ratio precision, actual balance, equity tracking and precise performance labels');
